### ISSUE TITLE
Probably a bug in data definition.

### ISSUE THREAD

**Issue by QianyangPeng** [kframework/wasm-semantics#100]
`rule \<k\> ( data MEMID IS:Instr    STRINGS ) => IS ~> data { MEMID  STRINGS } ... \</k\>`

This rule `IS` should be `Instrs`, not `Instr`. Also, "offset" should be `Instrs` rather than a single `Instr`

I am planning to fix this in the upcoming PR but if it is wrong please tell me

**Comment by hjorthjort** [comment]
I think actually only a single, constant instruction is allowed. See page 120 of the spec. It seems that the offset can be **either** a single instruction **or** `(offset IS)` where IS is a list of expressions, the way it's explained in section 6. But, I looked through the official tests, and found examples such as this:

`elem.wast`:
```
(assert_invalid
  (module
    (table 1 funcref)
    (elem (offset (nop) (i32.const 0)))
  )
  "constant expression required"
)
```

I couldn't find any valid examples of non-constant offsets

Here's the command line search I used to find all examples: `ag "\((data|elem)[^\(]*\([^)]+\)"`

**Comment by hjorthjort** [comment]
Looking at Section 3 on validation, offsets must be *constant* expressions (sections 3.4.5 and 3.4.6) of type `[i32]`.

Constant expressions are explained in section 3.3.7. Basically, they are either a `ITYPE.const` instruction, a `global.get` instruction, or a list of such instructions terminating in `end`.

Putting it together: offsets must be constant expression of type `[i32]`, i.e., a single constant instruction.  If we wanted to validate, we could write a simple `#isConst` function, but since we don't care about validation, we can check that it's only a single instruction.

**Comment by QianyangPeng** [comment]
I see. That makes sense
