### ISSUE TITLE
Module Implementation needs to reorganize semantics

### ISSUE THREAD

**Issue by QianyangPeng** [kframework/wasm-semantics#74]
There are some violates between the specs about modules and our current implementation:

1. According to the specs, the allocation of _functions_, _tables_, _memories_, _globals_, etc. are **not** instruction (you can never find them in sort Instrs in the specification!). Actually, they should be part of a module declaration. Instructions can only exist inside functions of .wast files, or inside codes of .js files.

2. According to the specs, when invoking a function, we **must** know the module that the function belongs to. A function cannot exist without a module. Otherwise, we cannot initialize the closure for the function.

Now we do not have these restrictions. That is to say everything is instruction, and functions could be everywhere. It currently makes things easy but it makes the implementation of module difficult. If we can make sure:

1. Allocations should always be inside modules.

2. Instructions (except invoke and call) should always be inside function.

I believe the semantics will become more accurate.

**Comment by ehildenb** [comment]
We want users to be able to use this semantics without declaring a module. This is so that it's easier for people to debug chunks of Wasm code without having an entire module or a large testing harness involving JavaScript.

We can make a super-sort of `Instr` called `Decl` if you like, but throwing everything in the `Instr` bin was intentional so that we can make the semantics more user-friendly.

**Comment by QianyangPeng** [comment]
According to the specs the function `allocmodule(𝑆, module, externval, val*)` is used as a helper function of the instantiation of modules. Currently in the specs module has no name field and `store` does not store the allocated module at all.

I think we should add another cell for module definitions. But several problems need to be addressed:

1. When should a module be put onto the `current Frame`? That is, when should a module be instantiated?

2. When a module is put onto the `current Frame`, what to do with the existing functions (also those other cells) defined on the `current Frame`? These functions could either defined in another module, or defined outside any module.

3. How to refer to a module if multiple modules are defined? Do we always overwrite the `moduleinst` with the latest module, or do we store all defined modules and use some identifier to distinguish them?

4. In the current implementation the `<fAddrs>` cell is not updated with the latest module state. So we need to use the address of cell, rather than copying the cell, to keep the function updated with the latest module state.

**Comment by hjorthjort** [comment]
Good points, I think we will need to make some modifications to current the call semantics. In general I think we can often get away with extending the semantics, though, to make sure that we still allow our interpreter to run programs outside of modules.

> According to the specs the function `allocmodule(𝑆, module, externval, val*)` is used as a helper function of the instantiation of modules. Currently in the specs module has no name field and `store` does not store the allocated module at all.
> 
> I think we should add another cell for module definitions. 

This has been my thinking recently as well. It would make sense to store the module definitions somewhere. In the spec the instances get passed around in full, but in the original paper, I think they let instances be represented by indexes, and then keep a global store of instances that they index into.

There's one thing I haven't really been able to understand about the spec: when a module has been fully defined, is it turned into an instance immediately? That seems to be how the reference interpreter works, but I guess an embedder (e.g., in JavaScript) would expect to be able to create several instances of the same module definition, so perhaps allocating instances and defining modules are different things?

Either way, I think we want a top-level cell called `<instances>` which maps integers to module instances. That way, a closure doesn't need to contain an entire module, but only needs an index into the `<instances>` cell. That should make the semantics more readable and definitions easier, since function definitions can be mutually recursive. I'm not an expert at `kprove`, but I would imagine it would also simplify proofs: whenever we refer to a module instance, we do so only by index, and two module references are the same iff they have the same index. Sort of like object equality in imperative languages, that just resolves to two objects variables being equal if they are the same pointer.

> But several problems need to be addressed:
> 
>     1. When should a module be put onto the `current Frame`? That is, when should a module be instantiated?
>

I don't think `<currentFrame>` should be for instantiation, but rather for calls into instances. A module instance gets put into the current frame when a function in it is being called, and the call frame is kept on the stack for later unwinding. In the spec, they call these stack objects `frame`. In the original paper, they call it `local`.

>     2. When a module is put onto the `current Frame`, what to do with the existing functions (also those other cells) defined on the `current Frame`? These functions could either defined in another module, or defined outside any module.

The way the spec does it is that a function invocation just puts a new `frame` on the stack, and relies on unspecified magic to restore the current frame after returning. I think for us a sensible option could be to put the index of the current module index either in the `frame` object, or on the stack right after, so that we can easily restore it without diverging from how `frame` is defined in the spec. The second option could look something like the following, after the configuration has been extended with an `<instances>` cell:

```
syntax Restore ::= "restore" Int 
--------------------------------
<k> restore I => . ... </k>
<instance>
  <iAddr> I </iAddr>
  <moduleInst> M </moduleInst>
</instance>
<currentFrame>
  <moduleInst> _ => M </moduleInst>
</currentFrame>
```

That's just a sketch of the idea. There are many ways we could implement it.

>     3. How to refer to a module if multiple modules are defined? Do we always overwrite the `moduleinst` with the latest module, or do we store all defined modules and use some identifier to distinguish them?
> 

I think the current frame is for the current execution context. Module definitions and instances, like you pointed out, should probably be stored elsewhere.

>     4. In the current implementation the `<fAddrs>` cell is not updated with the latest module state. So we need to use the address of cell, rather than copying the cell, to keep the function updated with the latest module state.

It looks to me like the current implementation of function calls assumes we are always in the same module, so the current frame isn't changed when calling into functions in other modules, if that's what you mean.

I think everything about the module "state" belongs in the store, right? That's where the memories, tables, globals, and functions are. So as long as everything else is just pointers into the store, we shouldn't need to worry about copying cell contents other than pointers. Not sure I fully understand the last sentence though, so please elaborate if you think I'm off target.

Good thoughts!

**Comment by QianyangPeng** [comment]
> ```
> syntax Restore ::= "restore" Int 
> --------------------------------
> <k> restore I => . ... </k>
> <instance>
>   <iAddr> I </iAddr>
>   <moduleInst> M </moduleInst>
> </instance>
> <currentFrame>
>   <moduleInst> _ => M </moduleInst>
> </currentFrame>
> ```

Can we declare two `moduleInst`s in different cells?

**Comment by hjorthjort** [comment]
No, you're right that cells need to have unique names. So one of the cells would need to be called something else.
