### ISSUE TITLE
About `types` and `modules`.

### ISSUE THREAD

**Issue by QianyangPeng** [kframework/wasm-semantics#87]
When people implicitly declare a type, it is not always the case that a new `functype` element will be added to the module instance. It will first find whether such an element is already in the module instance or not, and will reuse it if there is an existing one.

![image](https://user-images.githubusercontent.com/12062332/59211846-8711c000-8b76-11e9-9c51-953019c42e99.png)

As has been discussed earlier, when allocating a module, the declarations in it are not executed in order, and they are rearranged into the order of `types`->`functions`->`tables`->`memories`->`globals`. That is, even when the declarations of `types` are written after the declarations of `functions`, the `types` will be allocated before the `functions` are allocated. Here are some examples in `tests/wasm-tests/test/core/func.wast`:

```
(assert_invalid
  (module
    (func $f (result f64) (f64.const 0))  ;; adds implicit type definition
    (func $g (param i32))                 ;; reuses explicit type definition
    (func $h (result f64) (f64.const 1))  ;; reuses implicit type definition
    (type $t (func (param i32)))

    (func (type 2))  ;; does not exist
  )
  "unknown type"
)
```

In this case, declaring `func $g` in line 4 will not add a new type to the module instance, but it will reuse the declaration of `type $t` in line 6.

```
(module
  (func $f (result f64) (f64.const 0))  ;; adds implicit type definition
  (func $g (param i32))                 ;; reuses explicit type definition
  (type $t (func (param i32)))

  (func $i32->void (type 0))                ;; (param i32)
  (func $void->f64 (type 1) (f64.const 0))  ;; (result f64)
  (func $check
    (call $i32->void (i32.const 0))
    (drop (call $void->f64))
  )
)
```

In this case, `type 0` is [i32]->[void] and `type 1` is [void]->[f64], this is because line 4 of this module will be the first to be executed, letting the type for function `$f` allocated before the type for function `$g`.

Therefore, we may still need to distinguish `declarations` from `instructions`, because `instructions` are always executed in order but `declarations` are not.

**Comment by hjorthjort** [comment]
Good find. We can absolutely make declarations a subsort of instructions.

```
syntax Instr ::= Decl
syntax Decls ::= List{Decl, ""}
syntax Instr ::= "(" module Decls ")"
```
And then we would change something like

```
 syntax Instr ::= "(" "func"              FuncDecls Instrs ")"
 ...
```
into
```
 syntax Decl ::= "(" "func"              FuncDecls Instrs ")"
 ...
```

One way to tackle the ordering of different declarations is to add helpers called `filterTypes`, `filterFuncs`, etc., that will take all the contents of a module and keep just the type declarations, the func declarations, and so on. That should be fast in practice. But if you prefer something more algorithmically optimal, you could have a `groupDeclarations` function that takes the contents of a module and gives back 5 lists, one for each type of declaration, by collecting them in a single traversal. That function could assume that every instruction at the top level is a declaration, and thus a module that had any other instruction (like `i32.const`) at the top level would fail to be processed since there would be no rule to handle it.
