### ISSUE TITLE
Figure out a better solution for this

### ISSUE THREAD

**Issue by QianyangPeng** [kframework/wasm-semantics#98]
```k
    syntax Allocs ::= #ExtractTypes   ( Allocs )
                    | #ExtractFuncs   ( Allocs )
                    | #ExtractTables  ( Allocs )
                    | #ExtractMems    ( Allocs )
                    | #ExtractExports ( Allocs )
 // --------------------------------------------
    rule <k> #ExtractTypes   (                          .Allocs ) => .Allocs                              ... </k>
    rule <k> #ExtractTypes   ( TALLOC:TypeAlloc   ALLOCS:Allocs ) => TALLOC ~> #ExtractTypes ( ALLOCS )   ... </k>
    rule <k> #ExtractTypes   ( OLLOC:Alloc        ALLOCS:Allocs ) => #ExtractTypes ( ALLOCS )             ... </k> [owise]
    rule <k> #ExtractFuncs   (                          .Allocs ) => .Allocs                              ... </k>
    rule <k> #ExtractFuncs   ( FALLOC:FuncAlloc   ALLOCS:Allocs ) => FALLOC ~> #ExtractFuncs ( ALLOCS )   ... </k>
    rule <k> #ExtractFuncs   ( OLLOC:Alloc        ALLOCS:Allocs ) => #ExtractFuncs ( ALLOCS )             ... </k> [owise]
    rule <k> #ExtractTables  (                          .Allocs ) => .Allocs                              ... </k>
    rule <k> #ExtractTables  ( TALLOC:TableAlloc  ALLOCS:Allocs ) => TALLOC ~> #ExtractTables ( ALLOCS )  ... </k>
    rule <k> #ExtractTables  ( OLLOC:Alloc        ALLOCS:Allocs ) => #ExtractTables ( ALLOCS )            ... </k> [owise]
    rule <k> #ExtractMems    (                          .Allocs ) => .Allocs                              ... </k>
    rule <k> #ExtractMems    ( MALLOC:MemoryAlloc ALLOCS:Allocs ) => MALLOC ~> #ExtractMems ( ALLOCS )    ... </k>
    rule <k> #ExtractMems    ( OLLOC:Alloc        ALLOCS:Allocs ) => #ExtractMems ( ALLOCS )              ... </k> [owise]
    rule <k> #ExtractExports (                          .Allocs ) => .Allocs                              ... </k>
    rule <k> #ExtractExports ( EALLOC:ExportAlloc ALLOCS:Allocs ) => EALLOC ~> #ExtractExports ( ALLOCS ) ... </k>
    rule <k> #ExtractExports ( OLLOC:Alloc        ALLOCS:Allocs ) => #ExtractExports ( ALLOCS )           ... </k> [owise]
```

**Comment by hjorthjort** [comment]
Also see #87. Do we need to make a desugaring pass, or can we desugar dynamically?

**Comment by hjorthjort** [comment]
Here is a best-effort approach at coming up with what part of the module depends on each other. Blue is at instantiation time, red at declaration time.

Basically, at instantiation time, the allocations of tables must have been completed for elems to work, same for memory/data. Also, elem and data both require globals to have been initialized, since they may use constant expressions (which includes `global.get`) as offsets. Exports (which are allocations) rely on what they export having been allocated (so that they have an address to refer to). The other allocations are independent.

Globals could, in theory, be evaluated lazily, and just stored as instructions. But in a valid module, all imports must come before any globals, and globals may only refer to imported globals, so it shouldn't be a problem.

![deps](https://user-images.githubusercontent.com/8545447/60180554-994f5780-9820-11e9-87a7-c497354fb6d2.png)

Looking at the text format, it seems that all inline type declarations, import declarations and export declarations can be done when they are encountered because they only require that what they refer to has been allocated.
